name: Test Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - '*.cc'
      - '*.h'
      - binding.gyp
      - .github/workflows/build.yml
      - .github/workflows/validate_pull.yml

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Visual Studio Environment
        uses: egor-tensin/vs-shell@v2

      - name: Compile Library
        run: cl /O2 /std:c++17 /LD FileSystem.cc

      - name: Test Node.js Module
        run: npm i

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Library
        run: g++ -O2 -fPIC -shared -o FileSystem.so FileSystem.cc

      - name: Test Node.js Module
        run: npm i