name: Test Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - '*.cc'
      - '*.h'
      - binding.gyp
      - .github/workflows/build.yml
      - .github/workflows/validate_pull.yml

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4.2.1

      - name: Setup Visual Studio Environment
        uses: egor-tensin/vs-shell@v2.1

      - name: Compile
        run: |
          cl -O2 /Oi- /std:c++17 /LD FileSystem.cc
          npm i

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4.2.1

      - name: Compile
        run: |
          g++ -O3 -fno-builtin -fPIC -shared -o FileSystem.so FileSystem.cc
          npm i