name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - *.cc
      - *.h
      - module.gyp
      - package.json

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4.2.1

      - name: Compile Node.js Module
        run: npm i

      - name: Setup Visual Studio Environment
        uses: egor-tensin/vs-shell@v2.1

      - name: Compile
        run: cl -O2 -LD FileSystem.cc

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4.2.1

      - name: Compile Node.js Module
        run: npm i

      - name: Compile
        run: g++ -O3 -fPIC -shared -o FileSystem.so FileSystem.cc